### ISSUE TITLE
Unable to use the tool in a controlled env.

### ISSUE THREAD

**Issue by breachlabs-org** [MrEmpy/Reaper#1]
Hello, first thanks for your tool, secondly, i'm currently having issues with the tool.

Here's a bit of my process flow, 
- I have compiled with VS2022, i have put the driver and the compiled program in a directory i control, however, i keep receiving this error.
- I have also tested with the projects pre-compiled binaries and drivers, and have never been able to achieve the correct result.
- Currently running as Admin.
- Tested without AV and with AV
- Tested suspending and killing process either notepad or others.

```
c:\temp>ms-reaper.exe kp 1108
[*] The service already exists
[-] There was a problem opening the driver: 1314

c:\temp>sc stop Reaper

SERVICE_NAME: Reaper
        TYPE               : 1  KERNEL_DRIVER
        STATE              : 1  STOPPED
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0

c:\temp>sc delete Reaper
[SC] DeleteService SUCCESS

c:\temp>ms-reaper.exe kp 1108
[+] Service created and started successfully!
[-] There was a problem opening the driver: 1314
```

Would you have any suggestions on why it would cause such problem?
Thanks for your help.

**Comment by brosck** [comment]
Hello @brucebatman,

Have you tried running your terminal as administrator? Maybe that's why the program can't open the driver.

Regards,
\- MrEmpy

**Comment by breachlabs-org** [comment]
Hello @MrEmpy 

To answer your question, yes i have done it in elevated administrative shell, it is under my impression that loading drivers are done in an elevated context.

Thanks!

**Comment by brosck** [comment]
Hello @brucebatman,

Can you create a driver service manually and run it? Check if the ```SeLoadDriverPrivilege``` token belongs to your process in your terminal where you are trying to run. Are you running from Windows 10 operating system?

Regards,
\- MrEmpy

**Comment by breachlabs-org** [comment]
Works, with loading the SeLoadDriverPrivilege, in my process. 
Thanks again for your help.
